<center>
#  Facebook metrics Data Set

# Информация О Наборе Данных:

###  Данные относятся к публикациям, опубликованным в 2014 году на странице известного косметического бренда в Facebook. 

###  Этот набор данных содержит 500 из 790 строк и часть функций, проанализированных Moro et al. (2016). Остальные были опущены из-за проблем конфиденциальности.
###  Источник: Авторы: Серхио Моро, Пауло Рита и Бернардо Вала (ISCTE-IUL) @ 2016
### Данные состоят из 7 функций, известных до публикации, и 12 функций для оценки воздействия на публикацию. (см. Таблицы 2 и 3 Moro et al., 2016 - полная ссылка в «Запросе на цитирование»)


#### Характеристики Набора Данных: многомерные
#### Характеристики Атрибутов:  целое число
#### Задача: регрессия
#### Количество строк: 500
#### Количестно признаков: 19
#### Пропущенные значения: отсутствуют
#### Область: бизнес
#### Дата сбора выборки:05.08.2016
#### Количество обращений: 112858

### Признаки:
#### Общее число лайков, Тип(фото/статус), Категория, Месяц публикации, День публикации, Час публикации, Комерческий тип, Общее количество просмотров в течение с момента публикации, Общее количество просмотров с момента публикации, Количество пользователей просмотревшие данный пост, Число пользователей, Число потребителей, Оценка вашей страницы пользователями, Страница, Доступная пользователям публикация, которым нравится ваша страница, Пользователи, которым понравилась ваша страница, и которые перешли по вашей публикации, Количество коментариев, Количество лайков, Количество поделившихся данным постом, Общее количество взаимодействий.

Ссылка на dataset: https://archive.ics.uci.edu/ml/machine-learning-databases/00368/

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('datasetFacebook.csv',sep=";")
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
Page total likes                                                       500 non-null int64
Type                                                                   500 non-null object
Category                                                               500 non-null int64
Post Month                                                             500 non-null int64
Post Weekday                                                           500 non-null int64
Post Hour                                                              500 non-null int64
Paid                                                                   499 non-null float64
Lifetime Post Total Reach                                              500 non-null int64
Lifetime Post Total Impressions                                        500 non-null int64
Lifetime Engaged Users                                                 500 non-null int64
Lifetime Post Consumers                                                500 non-null int64
Lifetime Post Consumptions                                             500 non-null int64
Lifetime Post Impressions by people who have liked your Page           500 non-null int64
Lifetime Post reach by people who like your Page                       500 non-null int64
Lifetime People who have liked your Page and engaged with your post    500 non-null int64
comment                                                                500 non-null int64
like                                                                   499 non-null float64
share                                                                  496 non-null float64
Total Interactions                                                     500 non-null int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB